// Test settings
#define UDP_TX_BENCHMARK		0
#define TCP_LOOPBACK			1
#define TCP_LOOPBACK_MULTITASK	2

#define CURRENT_TEST	TCP_LOOPBACK

// network settings
#define MESSAGE_SIZE	1460
#define ETH_SERVER_PORT	55151

#define ETH_SERVER_IP_1	192
#define ETH_SERVER_IP_2	168
#define ETH_SERVER_IP_3	0
#define ETH_SERVER_IP_4	1
#define ETH_SERVER_IP	"192.168.0.1"

// LIS3DHTR
#define NO_OS		0
#define FREE_RTOS	1
#define LIS3DHTR_OS	FREE_RTOS
#define I2C_MEM_IT_FLAG		0x0002U
#define I2C_ERR_IT_FLAG		0x0004U

// MQTT
#define MQTT_OS_QUEUE_NUM_ELEMENTS 8
#define MQTT_OS_POOL_ELEMENT_SIZE 8

// other
#if CURRENT_TEST == TCP_LOOPBACK_MULTITASK
#define NUM_NETWORK_MESSAGES 16
#endif
