name: Sync shared directories and files

permissions:
  contents: write

concurrency:
  group: sync-shared
  cancel-in-progress: false

on:
  repository_dispatch:
    types: [sync_shared]

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout FreeRTOS_LwIP_MQTT repo
        uses: actions/checkout@v5

      - name: Update local branch
        run: |
          git pull --rebase origin main

      - name: Clone sensor_playground repo
        run: |
          git clone --depth 1 https://github.com/Manwlis/sensor_playground.git

      - name: Copy shared content
        run: |
          mkdir -p \
            code/Drivers/LIS3DHTR \
            code/Drivers/PmodALS \
            code/Middlewares/lwl \
            scripts

          rsync -av --delete \
            sensor_playground/code/CM7/Drivers/LIS3DHTR/ \
            code/Drivers/LIS3DHTR/

          rsync -av --delete \
            sensor_playground/code/CM7/Drivers/PmodALS/ \
            code/Drivers/PmodALS/

          cp sensor_playground/code/CM7/Core/lwl/lwl.c code/Middlewares/lwl/lwl.c
          cp sensor_playground/lwl_decoder.py scripts/lwl_decoder.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add \
            code/Drivers/LIS3DHTR \
            code/Drivers/PmodALS/ \
            code/Middlewares/lwl/lwl.c \
            scripts/lwl_decoder.py

          if ! git diff --cached --quiet; then
            git commit -m "Auto-sync shared directories and files"
            git push origin main
          fi
